services:
  spring-boot-app:
    build:
      dockerfile: docker/Dockerfile  # Dockerfile 경로 설정
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/adarticle-db  # MySQL URL
      SPRING_DATASOURCE_USERNAME: jinhan  # MySQL 사용자 이름
      SPRING_DATASOURCE_PASSWORD: 57575han  # MySQL 비밀번호
      SPRING_RABBITMQ_HOST: rabbitmq  # RabbitMQ 호스트
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/advertise-db  # MongoDB URL
    ports:
      - "8070:8070"  # Spring Boot 서버 포트를 외부에 노출
    depends_on:
      - mysql-db
      - mongodb
      - redis
      - logstash
      - rabbitmq
    networks:
      - app-network  # 다른 서비스와 통신하기 위한 네트워크 연결

  mysql-db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  # 로컬 my.cnf 파일을 MySQL 설정 파일로 사용
      - db_data:/var/lib/mysql  # 데이터 저장을 위한 볼륨 연결
    networks:
      - app-network  # 다른 서비스와 통신하기 위한 네트워크 연결
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  #
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    ports:
      - "${ES_PORT}:${ES_PORT}"
      - "${CLUSTER_ES_PORT}:${CLUSTER_ES_PORT}"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      ELASTIC_USERNAME: "jinhan"  # 환경 변수 설정 필요
      ELASTIC_PASSWORD: "57575han"
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: false
    networks:
      - app-network  # 다른 서비스와 통신하기 위한 네트워크 연결
    expose:
      - "${ES_PORT}" ## - 외부 접속 시 REST API 호출을 위한 포트
      - "${CLUSTER_ES_PORT}" ## - 클러스터 통신용 포트.

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    ports:
      - "9400:9400"
      - "${LOGSTASH_PORT_MAPPING}:${LOGSTASH_PORT_MAPPING}"
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_HOST=elasticsearch"
      - "ELASTICSEARCH_PORT=9200"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - app-network  # 다른 서비스와 통신하기 위한 네트워크 연결

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - app-network  # 다른 서비스와 통신하기 위한 네트워크 연결

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network  # 다른 서비스와 통신하기 위한 네트워크 연결

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"  # RabbitMQ 서버 포트
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"  # 관리 콘솔 포트
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}  # 기본 사용자 이름
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}  # 기본 사용자 비밀번호
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network  # 다른 서비스와 통신하기 위한 네트워크 연결

  mongodb:
    image: mongo:7
    container_name: mongodb-server
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongo_data:/data/db   # 데이터 저장을 위한 볼륨 연결
    networks:
      - app-network  # 다른 서비스와 통신하기 위한 네트워크 연결

volumes:
  db_data:  # MySQL 데이터
  es-data:  # Elasticsearch 데이터
  mongo_data:  # MongoDB 데이터
  redis-data:  # Redis 데이터
  rabbitmq_data:  # RabbitMQ 데이터

networks:
  app-network:
    driver: bridge