services:
  spring-server:
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/adarticle-db
      SPRING_DATASOURCE_USERNAME: jinhan
      SPRING_DATASOURCE_PASSWORD: 57575han
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/adarticle-db
    ports:
      - "8070:8070"
    depends_on:
      - mysql-db
      - mongodb
    ## 다음에 의존하는 서비스
    networks:
      - app-network  # 네트워크 설정 추가

  mysql-db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  # 로컬 my.cnf 파일을 MySQL 설정 파일로 사용
      - db_data:/var/lib/mysql  # 데이터 저장을 위한 볼륨 연결
    networks:
      - app-network
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
#    container_name: elasticsearch
#    ports:
#      - "${ES_PORT}:${ES_PORT}"
#      - "${CLUSTER_ES_PORT}:${CLUSTER_ES_PORT}"
#    volumes:
#      - ./data/elasticsearch:/usr/share/elasticsearch/data
#    environment:
#      discovery.type: single-node
#      ELASTIC_USERNAME: ${ELASTIC_USERNAME}  # 환경 변수 설정 필요
#      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
#      xpack.security.enabled: false
#      xpack.security.enrollment.enabled: false
#    networks:
#      - app-network
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.5.0
#    container_name: kibana
#    environment:
#      ELASTICSEARCH_HOSTS: "http://elasticsearch:${ES_PORT}"
#    ports:
#      - "${KIBANA_PORT}:${KIBANA_PORT}"
#    volumes:
#      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
#    networks:
#      - app-network
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.13.4
#    container_name: logstash
#    ports:
#      - "${LOGSTASH_PORT}:${LOGSTASH_PORT}"
#      - "${LOGSTASH_PORT_MAPPING}:${LOGSTASH_PORT_MAPPING}"
#    depends_on:
#      - elasticsearch
#    environment:
#      xpack.monitoring.enabled: false
#      LOGSTASH_JAVA_OPTS: "-Xms512m -Xmx512m"
#    volumes:
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#      - ./logstash/mysql-connector-j-9.0.0.jar:/usr/share/logstash/mysql-connector-j-9.0.0.jar
#    networks:
#      - app-network

  mongodb:
    image: mongo:7
    container_name: mongodb-server
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongo_data:/data/db   # 데이터 저장을 위한 볼륨 연결
    networks:
      - app-network   # app-network를 통해 네트워크에 연결

volumes:
  db_data:  # MySQL 데이터
  es-data:  # Elasticsearch 데이터
  mongo_data:  # MongoDB 데이터
  redis-data:  # Redis 데이터
  rabbitmq_data:  # RabbitMQ 데이터

networks:
  app-network:
    driver: bridge